language: java
dist: trusty

jdk:
  - oraclejdk8
  - oraclejdk9
  - openjdk10
  - openjdk11

notifications:
  email: false

# do not skip test step
script: "mvn install -Dmaven.javadoc.skip=true -B -V"
